on:
  push:
   /*what is the branch*/
    branches:
      - master



      jobs:
  build:
    
    runs-on: ubuntu-latest 
    
    steps:
      - name: "testing github actions"
        run: ls

      - uses: actions checkout@v3
      - name: "testing github actions"
        run: ls